### PR TITLE
Changing global variables to Singletons

### PR DESCRIPTION
**Pull request by cyberjacob**

### CODE REVIEW

**Comment by cyberjacob** [comment]
I origanaly meant to move that import to the start of the file, must have forgotten that but I've added it now.

For the `$db != null` check, this would always go through as the `db.inc.php` include always ensures there's an instance of `DatabaseConnection` available (line 630/631 of `db.inc.php`). If the database wasn't available (due to an upgrade or other problems), then `$db->$db` might be null?

I wonder if the globals could be reworked slightly to avoid this confusion?

**Comment by Forceu** [comment]
Sorry, in the `api.inc.php`  the  `require_once __DIR__ . "/db.inc.php";` cannot be moved to the top, as this automatically loads the DB. For the setup however, this must not happen, as no database is created yet / contains valid API entries. 

Regarding the `$db != null` check: There is a case where `$db` is null: When upgrading to a newer version of Barcode Buddy, `upgradeBarcodeBuddy()` in `db.inc.php` is being called. At that time, `$db` is null, as the function is called from the constructor. If the min Grocy version got changed, I am calling `isSupportedGrocyVersionOrDie()`, which calls the checkVersion function in `api.inc.php` - that one could however fail and then call the mentioned `logError()` function. At that point `$db` would be null, that is why we need the check there.

But yes, you are right, there should be a better way of handling the config, do you have any idea what we could use instead?

**Comment by cyberjacob** [comment]
ok not finished yet, but can I get your thoughts on the changes so far?
Basically moving DB and BBConfig to use a singleton pattern. This means that files that need to access the DB-stored config or the database itself can just include `config.inc.php` or `db.inc.php` respectively at the start of the file, and call `BBConfig::getInstance()` or `DatabaseConnection::getInstance()` when needed. I've also included an extra parameter for handling config checks during the DB connection to avoid getting stuck in a loop, and the bits you mentioned to avoid getting stuck during an upgrade.

**Comment by Forceu** [comment]
Looks very good so far! Using a Singleton is probably the best way to do it, thank you. I will review the code later today and then merge it.

**Pull request merged**
