### PR TITLE
Fix script inclusion

### PR DESCRIPTION
**Pull request by Teagan42**
**Purpose**
Fix logic for inclusion of checkbox on change script.

### CODE REVIEW

**Comment by Teagan42** [comment]
I literally picked up PHP yesterday - sorry for the misstep - simply negated the condition on accident at some point.

**Comment by Teagan42** [comment]
@Forceu is there an easier way to test changes than running the dev docker container? I'm not even sure how to startup a php app so I just have been spinning up a dev image every time I want to check a change.

**Comment by Forceu** [comment]
Thanks, that seems to work now. One more thing: In line 414 in uiEditor.php you wrote `($value && "checked")`, however that appends a "1" instead of a "checked", which means that the checkbox will never get checked. ;)

Yeah I am not a big fan of PHP to be honest, but it was the best choice at the time when I started the project.

The easiest way to setup a dev environment would be to install a webserver like Nginx or Apache2 (can be done on your computer or in a VM). See https://barcodebuddy-documentation.readthedocs.io/en/latest/setup.html#bare-metal

Alternatively you can install git on the Docker image with `apk add git` and then run `git pull` from within the container.

**Comment by Teagan42** [comment]
I’ll address that line in a few

**Comment by Forceu** [comment]
Hm that still didn't work. Unfortunately Github did not let me edit the PR, so I created a fix in bb26e8eb0a1725926f6586702d0ed8a113335359. Thanks :)

**Pull request closed without merging**
