### PR TITLE
Discogs provider

### PR DESCRIPTION
**Pull request by pwarren**
Implemented a Discogs lookup provider, have scanned in 30 of my CDs to test. Hope this is of assistance :)

### CODE REVIEW

**Comment by pwarren** [comment]
Have now scanned in >120 CDs, has been exactly what I wanted. Next up, my Movies and Books!

**Comment by Forceu** [comment]
Thanks, I will have a look at it tomorrow and probably merge it!

**Comment by Forceu** [comment]
According to the Discogs API documentation, no API key is needed. Is there a reason, why an API key field is in the menu?

**Comment by pwarren** [comment]
I think there are some endpoints that didn't require a token, but the search API does:

```
curl -s https://api.discogs.com/database/search?q=731344422424 | jq
{
  "message": "You must authenticate to access this resource."
}
curl -s "https://api.discogs.com/database/search?q=731344422424&token=$MYTOKEN" | jq .results[0].title
"Cherry Poppin' Daddies - Ferociously Stoned"
```

**Comment by pwarren** [comment]
And I did not get consistent results when using the /search?barcode=  endpoint, which also requires auth

**Comment by Forceu** [comment]
Ah got it. Thanks!

**Pull request merged**
