### PR TITLE
Add support for amounts with decimals / fractions

### PR DESCRIPTION
**Pull request by kuhlivisj**
Hi,

I've added support for decimals. It should solve a few open issues, like #115 and #138 and #122.
I hope I changed all the integer amounts being used in the code.

### CODE REVIEW

**Comment by Forceu** [comment]
Thanks a lot for your pull request! The automated testing showed some problems however, as some functions expect int and get float or vice versa:

https://github.com/Forceu/barcodebuddy/runs/4386791896?check_suite_focus=true

**Comment by kuhlivisj** [comment]
I fixed the problems the automated testing indicated. I also added an ignore on the missing parameter type. I hope you agree with that.

**Comment by Forceu** [comment]
Thanks a lot! I will test it in the coming days :)

**Comment by Forceu** [comment]
Thank you for your contribution and sorry the merge took so long!

**Pull request merged**
