### PR TITLE
Add mode change buttons to screen.php

### LINKED ISSUE #66: Feature Request: Touchscreen Keypad for mode selection, expiry date, and quantities
Would be useful for small devices utilising `screen.php` to be able to change the scanning mode (purchase/consume), enter the expiry dates for scanned products and enter specific quantities.

I'm happy to look into implementing this, though I'll leave it to you to decide how you want it to look/work first.

### PR DESCRIPTION
**Pull request by cyberjacob**
Click on the current mode to view them.

Does part of #66

### CODE REVIEW

**Comment by cyberjacob** [comment]
Ah I think my local copy was out of date, which would explain the `$BBCONFIG` issue. I'll make another PR in a few minutes to make Psalm complain about it.

`<?=` is a valid PHP tag, available in all supported versions, which echos the variable or statement inside it.

**Comment by Forceu** [comment]
> `<?=` is a valid PHP tag, available in all supported versions, which echos the variable or statement inside it.

Oh I didn't know that! I just saw that it did not work, I guess that was because the variable did not exist, not because of the tag.

I will review the changes on Monday, thank you!

**Comment by cyberjacob** [comment]
I think it must have been the variable that stopped it working. I was testing by just uploading that file to my k8s cluster, so will have been the slightly older stable version that doesn't have the new config stuff yet.

**Comment by Forceu** [comment]
Okay, so the buttons work now, thank you! Unfortunately it does not display correctly on a mobile device:



Also it would be probably a good idea to indicate that you can click there, maybe format it so it looks like a button? I could do that as well however.

**Comment by Forceu** [comment]
I added an own implementation in 57dba901ffda23b89fe6d2beee0e548eeeef22db, so this will be closed.
Thank you very much for your PR however!

**Pull request closed without merging**
